project:
  type: website
  output-dir: docs

website:
  favicon: images/jesus.png
  # x-card: true
  title: "blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kirubeltadesse
      - text: "{{< iconify streamline-logos:x-twitter-logo twitter >}}"
        href: https://x.com/kirubelmel
      - icon: linkedin
        href: https://linkedin.com/in/kirubeltadesse
      - text: "{{< iconify geo:ui-earth-west >}} "
        href: https://kirubeltadesse.github.io

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
