project:
  type: website
  output-dir: docs

website:
  favicon: images/jesus.png
  title: "Kirubel Tadesse"
  site-url: https://kirubeltadesse.github.io/blog/

  navbar:
    logo-href: https://kirubeltadesse.github.io/
    background: light
    pinned: true
    left:
      - text: "background"
        href: https://kirubeltadesse.github.io/background/
      - text: "projects"
        href: https://kirubeltadesse.github.io/projects/
      - text: "gallery"
        href: https://kirubeltadesse.github.io/gallery/
      - text: "contact"
        href: https://kirubeltadesse.github.io/contact/
      - text: "blogs"
        href: /
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kirubeltadesse
      - text: "{{< iconify streamline-logos:x-twitter-logo twitter >}}"
        href: https://x.com/kirubelmel
      - icon: linkedin
        href: https://linkedin.com/in/kirubeltadesse

  page-footer:
    background: dark
    center: |
      © 2024 Kirubel Tadesse

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
